name: HolisticVoiceCoach
favicon: null
layout_spectrum: 0.1805935448501259
typography_spectrum: 0.08090092614293098
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09559842804446816
  lightness: 0.8539992775768042
  saturation: 0.9612079921644181
  rhythmicContrast: 0.18905506585724652
purpose: []
